[package]
name = "clipboard_dictionary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk = "0.18.0"
gtk = "0.18.1"
mouse_position = "0.1.3"
webster = "0.3.0"
x11-clipboard = "0.9.1"
